# Generated by Django 5.2 on 2025-05-01 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''DROP SCHEMA IF EXISTS ai_sandbox CASCADE'''),
        migrations.RunSQL('''CREATE SCHEMA ai_sandbox'''),
        migrations.RunSQL('''CREATE FUNCTION ai_sandbox.org_user(global_user_id INTEGER)
        RETURNS TABLE(id org_user.id%TYPE, first_name org_user.first_name%TYPE, role org_user.role%TYPE)
        LANGUAGE sql  
        STABLE            
        SECURITY DEFINER  
        AS $$
        	WITH user_cte AS (SELECT "org_user"."id", "org_user"."role" FROM "org_user" WHERE "org_user"."id" = global_user_id)

SELECT "org_user"."id", "org_user"."first_name", "org_user"."role" FROM "org_user" WHERE ("org_user"."deactivated" IS NULL AND "org_user"."id" IN (CASE WHEN '(SELECT role FROM user_cte)' = 'AD' THEN (SELECT U0."id" AS "id" FROM "org_user" U0 WHERE U0."deactivated" IS NULL) ELSE (SELECT id FROM user_cte) END))
        $$;'''),
        migrations.RunSQL('''CREATE FUNCTION ai_sandbox.org_org(global_user_id INTEGER)
        RETURNS TABLE(id org_org.id%TYPE, name org_org.name%TYPE, type org_org.type%TYPE)
        LANGUAGE sql  
        STABLE            
        SECURITY DEFINER  
        AS $$
        	WITH user_cte AS (SELECT "org_user"."id", "org_user"."role" FROM "org_user" WHERE "org_user"."id" = global_user_id)

SELECT "org_org"."id", "org_org"."name", "org_org"."type" FROM "org_org" WHERE ('(SELECT role FROM user_cte)' = 'PB' AND "org_org"."type" IN ('AC'))
        $$;'''),
        migrations.RunSQL('''GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ai_sandbox TO mr_ai'''),
    ]
