# Generated by Django 5.2 on 2025-05-01 05:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL('''DROP SCHEMA IF EXISTS ai_sandbox CASCADE'''),
        migrations.RunSQL('''CREATE SCHEMA ai_sandbox'''),
        migrations.RunSQL('''CREATE FUNCTION ai_sandbox.org_user(global_user_id INTEGER)
        RETURNS TABLE(id org_user.id%TYPE, email org_user.email%TYPE, first_name org_user.first_name%TYPE, created org_user.created%TYPE, role org_user.role%TYPE)
        LANGUAGE sql 
        STABLE 
        SECURITY DEFINER 
        AS $$
        	WITH user_cte AS (SELECT "org_user"."id", "org_user"."role" FROM "org_user" WHERE "org_user"."id" = global_user_id)

SELECT "org_user"."id", "org_user"."email", "org_user"."first_name", "org_user"."created", "org_user"."role" FROM "org_user" WHERE ("org_user"."deactivated" IS NULL AND "org_user"."id" IN (CASE WHEN '(SELECT role FROM user_cte)' = 'AD' THEN (SELECT U0."id" AS "id" FROM "org_user" U0 WHERE U0."deactivated" IS NULL) ELSE (SELECT id FROM user_cte) END))
        $$;'''),
        migrations.RunSQL('''CREATE FUNCTION ai_sandbox.org_org(global_user_id INTEGER)
        RETURNS TABLE(id org_org.id%TYPE, name org_org.name%TYPE, created org_org.created%TYPE, type org_org.type%TYPE)
        LANGUAGE sql 
        STABLE 
        SECURITY DEFINER 
        AS $$
        	WITH user_cte AS (SELECT "org_user"."id", "org_user"."role" FROM "org_user" WHERE "org_user"."id" = global_user_id)

SELECT "org_org"."id", "org_org"."name", "org_org"."created", "org_org"."type" FROM "org_org" WHERE (('(SELECT role FROM user_cte)' = 'AD' AND "org_org"."type" IN ('AC', 'PE', 'IN')) OR ('(SELECT role FROM user_cte)' = 'AU' AND "org_org"."type" IN ('AC', 'PE')) OR ('(SELECT role FROM user_cte)' = 'PB' AND "org_org"."type" IN ('AC')))
        $$;'''),
        migrations.RunSQL('''CREATE FUNCTION ai_sandbox.org_worker(global_user_id INTEGER)
        RETURNS TABLE(id org_worker.id%TYPE, org_id org_worker.org_id%TYPE, created org_worker.created%TYPE, name org_worker.name%TYPE, type org_worker.type%TYPE, description org_worker.description%TYPE)
        LANGUAGE sql 
        STABLE 
        SECURITY DEFINER 
        AS $$
        	WITH user_cte AS (SELECT "org_user"."id", "org_user"."role" FROM "org_user" WHERE "org_user"."id" = global_user_id)

SELECT "org_worker"."id", "org_worker"."org_id", "org_worker"."created", "org_worker"."type", "org_worker"."name", "org_worker"."description" FROM "org_worker" WHERE ((('(SELECT role FROM user_cte)' = 'AD' AND "org_worker"."type" IN ('EM', 'CO', 'UA')) OR ('(SELECT role FROM user_cte)' = 'AU' AND "org_worker"."type" IN ('EM', 'CO')) OR ('(SELECT role FROM user_cte)' = 'PB' AND "org_worker"."type" IN ('EM', 'CO'))) AND "org_worker"."org_id" IN (SELECT U0."id" FROM "org_org" U0 WHERE (('(SELECT role FROM user_cte)' = 'AD' AND U0."type" IN ('AC', 'PE', 'IN')) OR ('(SELECT role FROM user_cte)' = 'AU' AND U0."type" IN ('AC', 'PE')) OR ('(SELECT role FROM user_cte)' = 'PB' AND U0."type" IN ('AC')))))
        $$;'''),
        migrations.RunSQL('''GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA ai_sandbox TO mr_ai'''),
    ]
