# Generated by Django 5.2 on 2025-04-22 02:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Org',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('AC', 'Active'), ('PE', 'Pending'), ('IN', 'Inactive')], default='AC', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('deactivated', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('AD', 'Admin'), ('AU', 'Authenticated'), ('PB', 'Public')], default='PB', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('EM', 'Employee'), ('CO', 'Contractor'), ('UA', 'Undercover Agent')], default='EM', max_length=2)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='org.org')),
            ],
        ),
    ]
